spring:

  application:
    name: api-rest-spring-boot

  datasource:
    url: jdbc:postgresql://localhost:5432/api-rest-spring-boot
    driver-class-name: org.postgresql.Driver
    username: ${PSQL_USER}
    password: ${PSQL_PASS}
    hikari:
      schema: tests

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

#  data:
#    web:
#      pageable:
#        default-page-size: 15
#        max-page-size: 100
#        page-parameter: page
#        size-parameter: size

  sql:
    init:
      mode: never # execute a sql script when the application starts

server:
  port: 8080
  error:
    include-message: never
    include-exception: off
    include-stacktrace: never



logging:
  level:
    root: debug

