spring:
  application:
    name: api-rest-spring-boot

  datasource:
    url: jdbc:postgresql://localhost:5432/api-rest-spring-boot
    driver-class-name: org.postgresql.Driver
    username: ${PSQL_USER}
    password: ${PSQL_PASS}
    hikari:
      schema: test

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true

  data:
    web:
      pageable:
        default-page-size: 15
        max-page-size: 100
        page-parameter: page
        size-parameter: size



debug: true

server:
  port: 8080
  error:
    include-message: always
    include-exception: off
    include-stacktrace: never



entities:
  user:

    constraints:
      unique:
        username:
          name: "username_unique"
          message: "Username already exists"
        email:
          name: "email_unique"
          message: "Email already exists"

    validations:
      username:
        length:
          max: 20
          message: "Username must be less than 20 characters" #TODO: test this
        not-blank:
          message: "Username mustn't be blank"

      password: # Length not because is encrypted
        not-blank:
          message: "Password mustn't be blank"

      email:
        not-blank:
          message: "Email is required"
        email-invalid:
          message: "Email is invalid"
